CREATE TABLE [dbo].[BOOKINGSROOMS](
	[BOOKINGSID] [bigint] NOT NULL,
	[ROOMSID] [smallint] NOT NULL,
 CONSTRAINT [PK_BOOKINGSROOMS] PRIMARY KEY CLUSTERED 
(
	[BOOKINGSID] ASC,
	[ROOMSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
