
CREATE TABLE [dbo].[BOOKINGS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CUSTOMERSID] [bigint] NOT NULL,
	[ROOMSID] [smallint] NULL,
	[QTYPERSONS] [smallint] NOT NULL,
	[STARTDATE] [date] NOT NULL,
	[ENDDATE] [date] NOT NULL,
	[ETA] [datetime] NULL,
	[TIMEARRIVAL] [datetime] NULL,
	[TIMEDEPARTURE] [datetime] NULL,
	[SPECIALNEEDS] [text] NULL,
	[EXTRABED] [bit] NOT NULL DEFAULT 0,
 CONSTRAINT [PK_BOOKINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY], 
    CONSTRAINT [FK_BOOKINGS_ROOMS] FOREIGN KEY ([ROOMSID]) REFERENCES [ROOMS]([ID]) 
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO