CREATE TABLE [dbo].[CUSTOMERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CUSTOMERTYPESID] [smallint] NOT NULL,
	[FIRSTNAME] [varchar](30) NOT NULL,
	[LASTNAME] [varchar](30) NOT NULL,
	[EMAIL] [varchar](60) NOT NULL,
	[STREETADRESS] [varchar](60) NOT NULL,
	[CITY] [varchar](30) NOT NULL,
	[COUNTRY] [varchar](30) NOT NULL,
	[PHONENUMBER] [varchar](30) NOT NULL,
	[ICE] [varchar](60) NULL,
	[LASTUPDATED] [datetime] NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY]
GO