CREATE TABLE [dbo].[CUSTOMERTYPES](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[TYPENAME] [varchar](30) NULL,
	[DISCOUNT(%)] [decimal](18, 0) NULL,
 CONSTRAINT [PK_CUSTOMERTYPES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO