CREATE TABLE [dbo].[ROOMS](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[ROOMNUM] [smallint] NOT NULL,
	[ROOMTYPESID] [smallint] NOT NULL,
 CONSTRAINT [PK_ROOMS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY]
GO