CREATE TABLE [dbo].[ROOMTYPES](
	[ID] [smallint] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](40) NOT NULL,
	[COST] [money] NOT NULL,
	[QTYBEDS] [smallint] NOT NULL,
 CONSTRAINT [PK_ROOMTYPES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO